### ISSUE TITLE
format check fails even though clang-format is happy

### ISSUE THREAD

**Issue by IgorMinar** [angular/gulp-clang-format#3]
[broccoli-typescript.ts](https://github.com/IgorMinar/angular/blob/c76a5148da0ce860428930d2c205aff8f084ae5e/tools/broccoli/broccoli-typescript.ts) keeps on failing the gulp `check-format` task in angular/angular even after the file has been formatted with clang-format and rerunning clang-format yields zero delta.

is it possible that the way the two streams are compared is not always reliable?

**Comment by alexeagle** [comment]
probably obsolete?
